### ISSUE TITLE
Unable to generate docset

### ISSUE THREAD

**Issue by Karrq** [Robzz/cargo-docset#10]
**Describe the bug**
Can't run the plugin in a workspace.
`Cargo doc error: failed to parse lock file at: /home/karrq/rust/project/Cargo.lock`

**To Reproduce**
`cargo docset`

**Expected behavior**
The program should run and generate a docset

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Documentation browser [e.g. dash, zeal]:  NA
 - Version: NA

**Additional context**
Normal `cargo doc` works great.
I tried other commands like specifying a single package but I still got the same error

**Comment by Robzz** [comment]
Thank you for the report. I never encountered that one so far despite using cargo-docset in workspaces, and the fact that cargo doc runs fine is certainly confusing, I'm gonna need some more information. Do you have the repository that causes the error online ? Being able to reproduce the problem would be a great start.

**Comment by Karrq** [comment]
I'm sorry but at this point in time the repository is private. I tried to make a minimal example with some path dependencies and some git dependencies and even colliding dependencies (one package depends on `rand@0.3` and the other `rand@0.4` but failed to do so...

**Comment by Robzz** [comment]
Yeah I've already tried these too, without problems. A minimal example would be very helpful indeed, at this point there's not much that I can do without it. Please let me know if you manage to create one.

**Comment by saskenuba** [comment]
This happened to me as well with the exact same error. The workaround I found was to rename Cargo.lock, generate the docset and then rename it back. 

Cargo doc generation works normally with Cargo.lock

**Comment by Robzz** [comment]
That's definitely interesting, thank you for the workaround. My guess is that the version of cargo cargo-docset links with probably can't understand the lock file generated by a more recent version of cargo that you use for development.

I could simply update the version of cargo we link against, but that would force me to release a new version for every new Rust release, which is less than ideal. Alternatively, I could remove the direct dependency on cargo and invoke it through `std::process::Command`, which may make things a bit more complicated and force me to rewrite part of the code, but would have the benefit of drastically cutting on the compile time for cargo-docset. I'll need to think on this when I'm a bit more awake, but at least we now know of a workaround in the meantime.

**Comment by joelparkerhenderson** [comment]
Same error message: "Cargo doc error: failed to parse lock file at: …/Cargo.lock"

You asked for a public repo: https://github.com/joelparkerhenderson/demo_rust_rocket

The repo is a typical demo of a typical Rust Rocket app, so I hope you can use it as a good example case. Rust Rocket does use Rust nightly, so perhaps that's relevant. And when I installed cargo-docset, it installed via Rust nightly.

The same error message is happening with my private Rocket repos as well.

**Comment by Robzz** [comment]
Alright, if this crate needs to constantly try and keep up with cargo releases in lockstep to avoid these issues, then I think the sane thing to do here for the sake of maintainability is probably to drop the cargo dependency and just invoke it as a subprocess. It's not like this crate _really_ needs to depend on cargo anyway, and cargo probably accounts for like 90% of the total compile time. I'll get on that ASAP.
