### ISSUE TITLE
cargo-docset does not support virtual manifest workspaces

### ISSUE THREAD

**Issue by lilyball** [Robzz/cargo-docset#25]
**Describe the bug**
When using a workspace that uses a [virtual manifest](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-manifest), `cargo-docset docset` panics with

```
thread 'main' panicked at 'Cargo.toml doesn't have a package table', src/commands/generate.rs:343:18
```

A virtual manifest workspace is one without a "root" package. `cargo doc` works just fine here (`cargo doc --workspace --open` just opens to the first crate in the workspace members list, but it includes all the crates).

It appears that cargo-docset is attempting to look up the root package name here. For virtual manifest workspaces, it would be really great if it could support a flag to provide a docset name, and default to the name of the containing folder. Until such time as `cargo doc` synthesizes a proper landing page for the docset, cargo-docset could just default to the first member crate exactly as `cargo doc` does (or it could synthesize a common landing page).

As a workaround, I can invoke `cargo-docset docset --all` from one of the member crates, but the resulting docset is named after that member crate.

**To Reproduce**

1. Make a virtual manifest workspace (a workspace whose `Cargo.toml` contains a `[workspace]` section but not a `[package]` section)
2. From the root of that workspace, run `cargo-docset docset`.

**Expected behavior**
It should build a docset for the workspace.

**Comment by Robzz** [comment]
Hi, thanks for the bug report. I'll try and look into that soon.

**Comment by Robzz** [comment]
It should now work. I haven't provided a flag to rename the docset yet, so the docset's name will be the same as the directory containing the virtual manifest, but it's one of the flags I was planning to add, I'll try to slip it in before the next release, as there's a couple of things I want to do before then. I'm hoping to ship the release by the end of next week :)
