### ISSUE TITLE
Every module has a spurious ::index suffix

### ISSUE THREAD

**Issue by lilyball** [Robzz/cargo-docset#29]
**Describe the bug**
I just built a docset for my workspace and deps, and to my surprise, all 860 modules have the suffix `::index`.

**To Reproduce**
I ran `cargo-docset docset --all` from within the first member crate of my workspace (due to #25), then opened the result in Dash.

**Expected behavior**
The modules list should be correct.

**Screenshots**
![Screen Shot 2021-04-29 at 4 15 04 PM](https://user-images.githubusercontent.com/714/116629421-127cd180-a906-11eb-8ef9-92af5f679d19.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3 (20D91)
 - Documentation browser: Dash 6.0.5
 - Version: cargo-docset 0.2.1

**Comment by Robzz** [comment]
Probably due to how the docset entries are created from the path of documentation html files, the `index.html` name of module files must leak through. Shouldn't be too hard a fix.
