### ISSUE TITLE
'cargo-docset' installed via 'cargo install' fails to run

### ISSUE THREAD

**Issue by klochowicz** [Robzz/cargo-docset#35]
**Describe the bug**
'cargo-docset' installed via 'cargo install' fails to run. The version built from github & installed from there works.

**To Reproduce**
`cargo install cargo-docset` 
`cargo docset`

**Expected behavior**
I'd expect the 'cargo docset' command to run instead of failing.

**Screenshots**

(pasted from the terminal, tried on few projects with the same result)

```
➜  Rocket git:(master) RUST_BACKTRACE=1 cargo docset
thread 'main' panicked at 'Cargo.toml doesn't have a package table', /Users/mariusz/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-docset-0.2.1/src/commands/generate.rs:343:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:1243:5
   3: cargo_docset::commands::generate::generate
   4: cargo_docset::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Desktop (please complete the following information):**
 - OS: macOS 11.5
 - Documentation browser [e.g. dash, zeal]: dash
 - Version: (version of OS or dash?)

**Comment by Robzz** [comment]
Yeah I really need to release a new version to crates.io. Will do soon.

**Comment by jiacai2050** [comment]
@Robzz It seems this issue stills there. 😭

**Comment by Robzz** [comment]
Sorry everyone, I haven't had time to do much Rust in quite a while and completely forgot about this. I''ll get a release out when I merge the PR I just opened, hopefully in the next couple days.

**Comment by Robzz** [comment]
I finally pushed a new release. Apologies for it having taken this long.
